### ISSUE TITLE
Invalid links to https://dberzano.github.io/alice/

### ISSUE THREAD

**Issue by vkucera** [alisw/alisw.github.io#98]
Invalid links to https://dberzano.github.io/alice/ in `./git-tutorial.markdown`, `./faq.markdown` should be replaced or deleted.

**Comment by vkucera** [comment]
@ktf

**Comment by ktf** [comment]
Done. Please do not open bug reports, but pull requests on how you think the documentation should be changed.

**Comment by vkucera** [comment]
> Done. Please do not open bug reports, but pull requests on how you think the documentation should be changed.

Thanks. I updated the link that could be updated, in my PR. I didn't find a replacement for the other links so it was not clear which changes to make.

**Comment by ktf** [comment]
Sure, just a place holder would have been fine. It simplifies the editing.
